### ISSUE TITLE
offizielle Übersetzung integrieren?

### ISSUE THREAD

**Issue by Vankog** [Prior99/cah-fullformat-german#2]
Heyho!
Ein Lob für dieses Projekt! Sehr gut gemacht. Läuft super durch und ist einfach zu erweitern.

Ich habe mal Ansatzweise die Karten der offiziell übernommenen Übersetzungen von cardsagainsthumanity.de hiermit verglichen. Sehe ich das richtig, dass viele der Karten bisher noch nicht dabei sind?
http://s3.amazonaws.com/cah/CAH_GermanByBalz.pdf
http://s3.amazonaws.com/cah/CAH_GermanByRaphael.pdf

Oder habt ihr irgendwo eine Liste, mit der man sowas abgleichen könnte?

**Comment by Prior99** [comment]
Hi,

when this was developed some years ago, official translations were not yet
available. I'd welcome a PR if no terms would be violated or be happy to
pass on maintenance of this.
